### ISSUE TITLE
.plot function Attribute Error

### ISSUE THREAD

**Issue by eRuaro** [lc5415/raceplotly#14] opened 2021-01-24 09:09 UTC
I was following along the tutorial on https://towardsdatascience.com/making-a-bar-chart-race-plot-using-plotly-made-easy-8dad3b1da955 and saw this error.

`AttributeError: 'NoneType' object has no attribute 'decode'`

How to recreate:
Run the following snippet of code.
```
import pandas as pd
from raceplotly.plots import barplot

data = pd.read_csv('https://raw.githubusercontent.com/lc5415/raceplotly/main/example/FAOSTAT_data.csv')

my_raceplot = barplot(data,
                      item_column='Item',
                      value_column='Value',
                      time_column='Year')

my_raceplot.plot(title = 'Top 10 Crops from 1961 to 2018',
                 item_label = 'Top 10 crops',
                 value_label = 'Production quantity (tonnes)',
                 frame_duration = 800)
```

Full error message will appear:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-84-07a4f36a1709> in <module>
----> 1 my_raceplot.plot(
      2                  item_label = 'Countries',
      3                  value_label = 'Total Cases Recorded',
      4                  frame_duration = 800)

C:\Users\Public\anaconda\lib\site-packages\raceplotly\plots.py in plot(self, title, orientation, initial_frame, value_label, item_label, time_label, frame_duration, date_format)
     43 
     44         # make frame1, the one that appears before the animation playy
---> 45         self.__make_frame1(initial_frame)
     46 
     47         # define ui: adds Play,Pause buttons and defines empty slider

C:\Users\Public\anaconda\lib\site-packages\raceplotly\plots.py in __make_frame1(self, time_frame1)
    185 
    186         # Create figure
--> 187         self.fig = go.Figure(
    188             data=[
    189                 go.Bar(

C:\Users\Public\anaconda\lib\site-packages\plotly\graph_objs\_figure.py in __init__(self, data, layout, frames, skip_invalid, **kwargs)
    594             is invalid AND skip_invalid is False
    595         """
--> 596         super(Figure, self).__init__(data, layout, frames, skip_invalid, **kwargs)
    597 
    598     def add_area(

C:\Users\Public\anaconda\lib\site-packages\plotly\basedatatypes.py in __init__(self, data, layout_plotly, frames, skip_invalid, **kwargs)
    631         # --------
    632         # ### Check for default template ###
--> 633         self._initialize_layout_template()
    634 
    635         # Process kwargs

C:\Users\Public\anaconda\lib\site-packages\plotly\basedatatypes.py in _initialize_layout_template(self)
   2519                     else:
   2520                         # Name of registered template object
-> 2521                         template_object = pio.templates[pio.templates.default]
   2522                     self._layout_obj.template = template_object
   2523                 finally:

C:\Users\Public\anaconda\lib\site-packages\plotly\io\_templates.py in __getitem__(self, item)
     87                         "package_data", "templates", template_name + ".json"
     88                     )
---> 89                     template_str = pkgutil.get_data("plotly", path).decode("utf-8")
     90                     template_dict = json.loads(template_str)
     91                     template = Template(template_dict, _validate=False)

AttributeError: 'NoneType' object has no attribute 'decode'
```

Error is at the `plot` function

**Comment by lucharo** [comment] 2021-01-24 10:04
Hi @eRuaro thanks for reporting a bug, I'll look into this today!

**Comment by lucharo** [comment] 2021-01-24 22:34
@eRuaro could you share the output of `conda list` if you're using a conda environment or `pip freeze` if you are using a virtualenv or other sort of environment?

I am unable to reproduce your error with the latest `raceplotly` version (0.1.5) and python 3.8.5.

**Comment by eRuaro** [comment] 2021-01-24 23:39
Hi, @lc5415 ! Sorry for the hassle, I got it to work just a minute ago in Google Colabs. However, in the `item_column`, is there a way to make it plot multiple columns instead of one?

**Comment by lucharo** [comment] 2021-01-25 09:27
Mmm, would you like to base the ranking on several columns or make two separate plots? Otherwise each plot will only include a single ranking hence a single `item_colum`

**Comment by lucharo** [comment] 2021-01-25 09:29
I am closing this issue as the issue itself is resolved!

**Closed as completed by lucharo** 2021-01-25 09:29 UTC
